import { readFile, writeFile } from 'node:fs/promises';
import iconv from 'iconv-lite';

import { parseDbc, writeExcel, validate, IOError } from '@dbc-forge/core';
import { Command } from 'commander';

import { renderIssues } from '../render/issues.js';

interface ExtractOptions {
  output: string;
  validate: boolean;
  quiet?: boolean;
}

export const extractCommand = new Command('extract')
  .description('DBC → Excel 通信矩阵')
  .argument('<input.dbc>', 'input DBC file')
  .requiredOption('-o, --output <file>', 'output Excel file')
  .option('--no-validate', 'skip validation (extract mode is permissive)')
  .option('--quiet', 'suppress warnings')
  .action(async (input: string, opts: ExtractOptions) => {
    let text: string;
    try {
      // DBC files generated by Vector / CANdb++ on Windows are typically
      // saved in the system ANSI code page (CP936 / GBK for zh-CN), not
      // UTF-8. Decoding as utf-8 turns every GBK byte into U+FFFD and
      // destroys all Chinese comments / unit strings. Decode as 'latin1'
      // (1 byte → 1 char) first, then re-decode each line as GBK so the
      // parser sees a clean UTF-16-ish string with CJK correctly recovered.
      const buf = await readFile(input);
      text = buf.toString('latin1');
      // Quick probe: if the latin1 string contains no high bytes (all ASCII),
      // it's already valid UTF-8 / ASCII — skip GBK round-trip.
      if (/[\x80-\xff]/.test(text)) {
        // Re-decode the raw bytes as GBK via iconv-lite. Node 24's small-icu
        // build drops GBK, so we use iconv-lite's pure-JS tables.
        text = iconv.decode(buf, 'gbk');
      }
    } catch (e) {
      throw new IOError('cannot read input', { path: input, cause: e });
    }
    const net = parseDbc(text);
    if (opts.validate) {
      const r = validate(net, { mode: 'extract' });
      if (r.errors.length > 0) {
        process.stderr.write(renderIssues([...r.errors, ...r.warnings]) + '\n');
        process.exit(1);
      }
      if (!opts.quiet && r.warnings.length > 0) {
        process.stderr.write(renderIssues(r.warnings) + '\n');
      }
    }
    const buf = await writeExcel(net);
    try {
      await writeFile(opts.output, buf);
    } catch (e) {
      throw new IOError('cannot write output', { path: opts.output, cause: e });
    }
  });
